# Generated by Django 3.1.4 on 2020-12-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201203_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripton',
            new_name='description',
        ),
    ]
